# meta-linux-fpga-robot layer

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "linux-fpga-robot"
BBFILE_PATTERN_linux-fpga-robot = "^${LAYERDIR}/"
BBFILE_PRIORITY_linux-fpga-robot = "6"

LAYERSERIES_COMPAT_linux-fpga-robot = "scarthgap"